--!strict

return table.freeze({
	BaseWalkSpeed = 20,
	MinimumLoadedWalkSpeed = 9.5,
	GrabDistance = 10,
	TechnicalMaxItems = 28,
	DroppedItemProtectionSeconds = 2.5,

	Beginner = table.freeze({ Strength = 15, CarrySpace = 13, Control = 1.0 }),
	Veteran = table.freeze({ Strength = 38, CarrySpace = 28, Control = 2.2 }),

	-- Speed upgrades remain useful while carrying. Weight still suppresses the
	-- bonus, but progressed players retain enough of it that long-map extraction
	-- does not collapse back toward starter travel speed.
	Mobility = table.freeze({
		SuppressionStartWeightRatio = 0.35,
		FullSuppressionWeightRatio = 1.35,
		MinimumBonusFractionAtMaxLoad = 0.65,
		LoadedMinimumBonusFraction = 0.50,
	}),

	Movement = table.freeze({
		VelocityDeadzone = 1.4,
		AccelerationDeadzone = 8,
		TurnMinimumSpeed = 3.5,
		TurnAngleDeadzoneDegrees = 7,
		AccelerationGain = 0.075,
		TurnGain = 0.82,
		MovingRecoveryRate = 0.95,
		StoppedRecoveryRate = 3.8,
		MovementOscillationScale = 0.22,
		WideTurnMultiplierPerItem = 0.14,
		MaxDynamicSway = 1.35,
		VisualUpdateHz = 24,
		StateUpdateHz = 10,
	}),

	-- High speed is not the punishment. Abrupt velocity change is. The runtime
	-- motion layer amplifies acceleration, braking, sharp turns and reversals,
	-- while smooth cruising settles back toward ordinary carry behavior.
	SpeedHandling = table.freeze({
		CruiseSettleSeconds = 0.65,
		CruiseAccelerationTolerance = 7.0,
		CruiseTurnToleranceDegrees = 5.0,
		CruiseMinimumSpeed = 10.0,

		AccelerationStart = 12.0,
		AccelerationFull = 85.0,
		BrakeSpeedDropStart = 4.0,
		BrakeSpeedDropFull = 22.0,
		TurnStartDegrees = 8.0,
		TurnFullDegrees = 90.0,
		ReversalDegrees = 145.0,

		SpeedAmplificationStart = 20.0,
		SpeedAmplificationFull = 88.0,
		MaximumEventSwayMultiplier = 1.85,
		MinimumEventRecoveryMultiplier = 0.52,
		ControlReductionExponent = 0.72,
		EventDecayPerSecond = 5.5,
	}),

	BaseInstability = table.freeze({
		WeightPressureStart = 0.68,
		WeightPressureScale = 0.65,
		BulkPressureStart = 0.72,
		BulkPressureScale = 0.52,
		LayerContribution = 0.05,
		TallBaseContribution = 0.02,
		TallLayerContribution = 0.04,
		WideContribution = 0.045,
		HighWeightPerLayer = 0.02,
		ControlExponent = 0.55,
		MaxBaseInstability = 1.30,
	}),

	Danger = table.freeze({
		SlightWobble = 0.26,
		Unstable = 0.46,
		Dangerous = 0.68,
		NearCollapse = 0.84,
		CollapseRisk = 0.98,
		RecoveryRisk = 0.70,
		MinimumBaseForCollapse = 0.40,
		MinimumSwayForCollapse = 0.15,
		SwayRiskScale = 0.80,
		CollapseWarningSeconds = 1.05,
		RecoveryFeedbackMinWarningSeconds = 0.38,
		RecoveryFeedbackCooldownSeconds = 2.25,
	}),

	Strain = table.freeze({
		Max = 1.0,
		StartWeightRatio = 0.85,
		FullWeightRatio = 1.50,
		StartBulkRatio = 0.90,
		FullBulkRatio = 1.60,
		StartBaseInstability = 0.50,
		FullBaseInstability = 1.15,
		StartLayer = 3,
		FullLayer = 7,
		WeightWeight = 0.30,
		BulkWeight = 0.25,
		BaseWeight = 0.35,
		HeightWeight = 0.10,
		PeakPressureWeight = 0.60,
		CombinedPressureWeight = 0.40,
		MinimumLoadSeverity = 0.10,
		MaxAccumulationPerSecond = 0.070,
		AccumulationExponent = 1.25,
		ComfortDecayPerSecond = 0.080,
		UnloadedRecoveryPerSecond = 0.140,
		Moderate = 0.30,
		High = 0.62,
		Critical = 0.86,
		SwayGenerationMultiplierAtMax = 1.55,
		MinimumRecoveryMultiplierAtMax = 0.48,
		TremorStart = 0.24,
		TremorAmplitudeAtMax = 0.30,
		TremorFrequency = 7.0,
		TremorVerticalRatio = 0.65,
		VisualShakeAtMax = 0.065,
		TutorialMessageStrain = 0.12,
	}),

	Ditch = table.freeze({ ScatterSeconds = 0.34, VisualLifetimeSeconds = 2.4, FadeSeconds = 0.40 }),

	Failure = table.freeze({
		Mode = "ScaledPartialCollapse",
		MinimumDroppedItems = 1,
		CollapseScatterSeconds = 0.34,
		LostVisualLifetimeSeconds = 2.2,
		MinorSeverityMax = 0.24,
		SevereSeverityMin = 0.68,
		NormalLossFraction = 0.30,
		SevereLossFraction = 0.55,
		RiskOvershootForMaxSeverity = 0.40,
		BaseInstabilityForMaxSeverity = 1.15,
		ExtraWarningSecondsForMaxSeverity = 1.20,
		RiskSeverityWeight = 0.48,
		BaseSeverityWeight = 0.32,
		TimeSeverityWeight = 0.20,
	}),

	Stack = table.freeze({
		ItemsPerLayer = 2,
		LayerHeight = 3.65,
		BaseForwardOffset = -2.15,
		BaseHeight = 0.55,
		SideSpacing = 2.55,
		LayerSpreadPerLevel = 0.22,
		WideExtraSpread = 1.05,
		WideForwardOffset = 0.55,
		CompactYawDegrees = 7,
		TallOutwardRollDegrees = 5,
		WideYawDegrees = 13,
		WideRollDegrees = 6,
		MaxVisualLeanDegrees = 13,
		MaxVisualPitchDegrees = 8,
		MaxVisualOffsetStuds = 0.26,
		LayerSwayAmplification = 0.24,
		LayerFollowRate = 10,
		LayerLagPerLevel = 1.15,
		MinimumLayerFollowRate = 3.8,
		MaxLayerVisualMultiplier = 2.35,
		NearCollapseShake = 0.10,
		NearCollapseShakeSpeed = 8.5,
		NearCollapseSlipStuds = 0.55,
	}),

	Feel = table.freeze({
		GrabTweenBaseSeconds = 0.12,
		GrabTweenPerWeightSeconds = 0.012,
		GrabRecoilBase = 0.018,
		GrabRecoilPerWeightRatio = 0.18,
		GrabRecoilPerBulkRatio = 0.07,
		UnloadTweenSeconds = 0.28,
		UnloadStaggerSeconds = 0.025,
	}),
})
