--!strict

return table.freeze({
	BaseWalkSpeed = 16,
	MinimumLoadedWalkSpeed = 9.5,
	GrabDistance = 10,
	TechnicalMaxItems = 28,
	DroppedItemProtectionSeconds = 2.5,

	Beginner = table.freeze({
		Strength = 15,
		CarrySpace = 13,
		Control = 1.0,
	}),

	Veteran = table.freeze({
		Strength = 38,
		CarrySpace = 28,
		Control = 2.2,
	}),

	Movement = table.freeze({
		VelocityDeadzone = 1.4,
		AccelerationDeadzone = 8,
		TurnMinimumSpeed = 3.5,
		TurnAngleDeadzoneDegrees = 7,
		AccelerationGain = 0.075,
		TurnGain = 0.82,
		MovingRecoveryRate = 0.82,
		StoppedRecoveryRate = 3.8,
		MovementOscillationScale = 0.22,
		WideTurnMultiplierPerItem = 0.14,
		MaxDynamicSway = 1.35,
		VisualUpdateHz = 24,
		StateUpdateHz = 10,
	}),

	BaseInstability = table.freeze({
		WeightPressureStart = 0.68,
		WeightPressureScale = 0.65,
		BulkPressureStart = 0.72,
		BulkPressureScale = 0.52,
		LayerContribution = 0.05,
		TallBaseContribution = 0.02,
		TallLayerContribution = 0.04,
		WideContribution = 0.045,
		HighWeightPerLayer = 0.02,
		ControlExponent = 0.55,
		MaxBaseInstability = 1.30,
	}),

	Danger = table.freeze({
		SlightWobble = 0.26,
		Unstable = 0.46,
		Dangerous = 0.68,
		NearCollapse = 0.84,
		CollapseRisk = 0.98,
		RecoveryRisk = 0.70,
		MinimumBaseForCollapse = 0.40,
		MinimumSwayForCollapse = 0.15,
		SwayRiskScale = 0.80,
		CollapseWarningSeconds = 1.05,
		RecoveryFeedbackMinWarningSeconds = 0.38,
		RecoveryFeedbackCooldownSeconds = 2.25,
	}),

	Failure = table.freeze({
		Mode = "PartialCollapse",
		PartialCollapseFraction = 0.35,
		MinimumDroppedItems = 1,
		CollapseScatterSeconds = 0.34,
	}),

	Stack = table.freeze({
		ItemsPerLayer = 2,
		LayerHeight = 3.65,
		BaseForwardOffset = -2.15,
		BaseHeight = 0.55,
		SideSpacing = 2.55,
		LayerSpreadPerLevel = 0.22,
		WideExtraSpread = 1.05,
		WideForwardOffset = 0.55,
		CompactYawDegrees = 7,
		TallOutwardRollDegrees = 5,
		WideYawDegrees = 13,
		WideRollDegrees = 6,
		MaxVisualLeanDegrees = 13,
		MaxVisualPitchDegrees = 8,
		MaxVisualOffsetStuds = 0.26,
		LayerSwayAmplification = 0.24,
		LayerFollowRate = 10,
		LayerLagPerLevel = 1.15,
		MinimumLayerFollowRate = 3.8,
		MaxLayerVisualMultiplier = 2.35,
		NearCollapseShake = 0.10,
		NearCollapseShakeSpeed = 8.5,
		NearCollapseSlipStuds = 0.55,
	}),

	Feel = table.freeze({
		GrabTweenBaseSeconds = 0.12,
		GrabTweenPerWeightSeconds = 0.012,
		GrabRecoilBase = 0.018,
		GrabRecoilPerWeightRatio = 0.18,
		GrabRecoilPerBulkRatio = 0.07,
		UnloadTweenSeconds = 0.28,
		UnloadStaggerSeconds = 0.025,
	}),
})
